FROM python:3.8-slim

WORKDIR /app

COPY . /app
RUN chmod +x /app/frames.sh
EXPOSE 7777

RUN apt-get update && \
    apt-get install -y gcc python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir opencv-python-headless jupyter notebook


CMD ["/bin/bash", "-c", "./frames.sh"]


