version: '3.8'

services:
  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "80:80"
      - "9999:9999"
    volumes:
      - ./src:/app/src
    command: /bin/bash -c "./startup.sh & uvicorn src.youtubeDownloader:app --host 0.0.0.0 --port 80 & jupyter notebook --ip 0.0.0.0 --port 9999 --no-browser --allow-root"

  pytorch-service:  
    build:
        context: .
        dockerfile: Dockerfile.pytorch
    platform: linux/amd64
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter notebook --notebook-dir=/app --ip='*' --port=8888 --no-browser --allow-root

  python-service:
    image: python:3.8-slim
    build:
      context: .
      dockerfile: Dockerfile.frames
    ports:
      - "90:90"
      - "7777:7777"
    volumes:
      - ./Video_Search_Assignment/Downloads/YouTube-Videos/:/app/Video_Search_Assignment/Downloads/YouTube-Videos/
    command: /bin/bash -c "./frames.sh"

