
FROM tensorflow/tensorflow:latest-gpu-jupyter


RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install numpy matplotlib

WORKDIR /app

COPY . /app

EXPOSE 8888
RUN pip install jupyter
RUN pip install notebook

CMD ["jupyter", "notebook", "--ip='*'", "--port=8888", "--no-browser", "--allow-root"]
