FROM python:3.9-slim

WORKDIR /app

RUN pip install torch torchvision

RUN pip install samgeo
RUN pip install rasterio  # Assuming rasterio might be needed for geotiff handling

COPY . /app

CMD ["python", "mask.py"]
